import { useState } from "react";
import { nbsFields, nbsReplay, originalNbs, type NbsConfig } from "../../content/lessons/newborn-screen-to-public-health/interaction";
import { Teaching, Topic5Section, Topic5Select, type Topic5Props } from "./Topic5Common";

export function NewbornExperience({ Concepts, Bridge, onAttempt }: Topic5Props) {
  const [config, setConfig] = useState({ ...originalNbs });
  const [tested, setTested] = useState(false);
  const [review, setReview] = useState(false);
  const results = nbsReplay(config);
  const passed = results.filter(row => row.pass).length;
  return <div>
    <Topic5Section title="Compare the received report with the interface agreement"><article className="artifact-card topic5-record"><h3>Receiver record · NB-01 · 08:41</h3><dl><dt>Message control ID</dt><dd>N001</dd><dt>Infant identifier / authority</dt><dd>004812 / NRH</dd><dt>Specimen / report version</dt><dd>DBS-081 / 1</dd><dt>Observation identifier</dt><dd>NBS_SUM · local dictionary</dd><dt>Answer / status</dt><dd>REFERRAL · local text / final</dd><dt>Application acknowledgment</dt><dd>AA · N001 · stored</dd><dt>Routing service</dt><dd>Exception: no matching coded interpretation rule</dd></dl></article><Teaching Content={Concepts}/></Topic5Section>
    <Topic5Section title="Configure the receiver profile"><div className="topic5-controls">{nbsFields.map(field => <Topic5Select key={field.key} label={field.label} value={config[field.key]} options={field.options} note={(field.notes as Record<string,string>)[config[field.key]]} onChange={value => { setConfig({ ...config, [field.key]: value } as NbsConfig); setTested(false); setReview(false); }}/>)}</div><article className="artifact-card topic5-record"><h3>NB-01 proposed coded fields</h3><p>Observation: <code>{config.observation === "overall" ? "57130-7 / LN" : config.observation === "condition" ? "46746-4 / LN" : "NBS_SUM / local"}</code></p><p>Answer: <code>{config.answers === "coded" ? "LA25817-0 / LN" : "REFERRAL / local text"}</code></p><p role="status">Receiver action: <strong>{results[0].action}</strong></p></article><button className="primary-button" type="button" onClick={() => { setTested(true); onAttempt?.(true); }}>Replay eight message situations</button><p role="status">{tested ? `${passed} of 8 receiving actions match.` : "Run the original configuration, then compare the complete repair."}</p><div className="rule-result-list">{results.map(row => <details key={row.id} className={tested ? row.pass ? "pass" : "fail" : "pending"}><summary>{row.id} · {row.answer} · {row.status}{tested && <strong>{row.action} · {row.pass ? "Matches" : "Does not match"}</strong>}</summary><p>Identity authority: {row.identity ? "present" : "missing"}; exact retransmission: {row.duplicate ? "yes" : "no"}.</p><p>Expected: <strong>{row.expected}</strong>. {row.note}</p></details>)}</div></Topic5Section>
    <Topic5Section title="Confirm program follow-up"><Teaching Content={Bridge}/><label className="topic5-check"><input type="checkbox" checked={review} onChange={event => setReview(event.target.checked)}/>Include worklists, exception ownership, and correction reconciliation in acceptance testing.</label>{review && <p className="topic5-note" role="status">{tested && passed === 8 ? "The replay supports joint laboratory and program acceptance review." : "The receiving actions must match before this configuration is ready for acceptance review."}</p>}</Topic5Section>
    <button className="text-button" type="button" onClick={() => { setConfig({ ...originalNbs }); setTested(false); setReview(false); onAttempt?.(false); }}>Reset lesson interactions</button>
  </div>;
}
