import { useState } from "react";
import { originalQueue, queuePlans, queueReport, queueSources, timeText, type QueueConfig } from "../../content/lessons/invisible-bottleneck/interaction";
import { SourceInspector, Teaching, Topic5Section, Topic5Select, type Topic5Props } from "./Topic5Common";

export function QueueExperience({ Concepts, Bridge, onAttempt }: Topic5Props) {
  const [config, setConfig] = useState<QueueConfig>({ ...originalQueue });
  const [plan, setPlan] = useState("");
  const report = queueReport(config);
  function update(key: keyof QueueConfig, value: string) { setConfig({ ...config, [key]: value }); setPlan(""); onAttempt?.(true); }
  const ready = config.freshness === "current" && config.source === "linked" && config.stage === "post" && plan === "coverage";
  return <div><Topic5Section title="Inspect the source and refresh records"><SourceInspector records={queueSources}/></Topic5Section><Topic5Section title="Rebuild the dashboard comparison"><Teaching Content={Concepts}/><div className="topic5-controls">
    <Topic5Select label="Extract time" value={config.freshness} options={[["stale","09:00 · scheduled extract"],["current","12:00 · review extract"]]} onChange={value => update("freshness",value)} note={config.freshness === "stale" ? "The 10:00 delivery has not occurred in this snapshot." : "The review extract includes the later delivery and events available at noon."}/>
    <Topic5Select label="Record sources" value={config.source} options={[["lis","Finalized results only"],["linked","Linked operational records"]]} onChange={value => update("source",value)} note={config.source === "lis" ? "The completed-result statistics cannot show unfinished work. The audit comparison reports how many received accessions this view omits." : "Unfinished accessions remain visible with elapsed ages, separate from completed-duration statistics."}/>
    <Topic5Select label="Arrival group" value={config.period} options={[["all","All selected arrivals"],["peak","10:00 courier group"]]} onChange={value => update("period",value)} note="The selection changes the denominator. Compare the same group before interpreting a difference."/>
    <Topic5Select label="Time interval" value={config.stage} options={[["total","Receipt to release"],["analysis","Receipt to analysis"],["post","Analysis to release"]]} onChange={value => update("stage",value)} note={config.stage === "post" ? "This interval includes waiting and review after the analyzer finished." : config.stage === "analysis" ? "This includes pre-analysis waiting and preparation, not just instrument processing." : "Only released records have a completed total duration."}/>
    </div><div className="topic5-dashboard" role="status"><p>Data as of <strong>{timeText(report.cutoff)}</strong> · {config.period === "all" ? "all selected arrivals" : "10:00 courier group"}</p><p><strong>{report.complete.length} completed</strong> · {report.pending.length} pending shown · {report.omitted} unfinished omitted</p><p>Completed median: <strong>{report.median ?? "Not available"}{report.median !== null && " min"}</strong> · 90th percentile: <strong>{report.p90 ?? "Not available"}{report.p90 !== null && " min"}</strong></p></div>
    <div className="topic5-duration-bars" aria-label="Completed durations in accession order">{report.complete.map(row => <div key={row.id}><span>{row.id}</span><span className="topic5-bar" style={{ width: `${Math.max(2,report.duration(row))}%` }} aria-hidden="true"/><strong>{report.duration(row)} min</strong></div>)}</div>
    <div className="topic5-table-wrap"><table><caption>Selected records · times on the review day. Minutes show the completed interval, or age since receipt for pending results.</caption><thead><tr><th>ID</th><th>Receipt</th><th>Analysis</th><th>Release</th><th>Minutes</th></tr></thead><tbody>{[...report.complete,...report.pending].map(row => <tr key={row.id}><th scope="row">{row.id}</th><td>{timeText(row.received)}</td><td>{timeText(row.analyzed)}</td><td>{row.released === null ? "Pending" : timeText(row.released)}</td><td>{row.released === null ? `${report.cutoff-row.received} min open` : `${report.duration(row)} min`}</td></tr>)}</tbody></table></div>{report.complete.length === 0 && <p>No completed records from this group are available in the selected snapshot.</p>}</Topic5Section>
    <Topic5Section title="Choose an intervention and its measures"><Teaching Content={Bridge}/><fieldset className="topic5-plan"><legend>Operational recommendation</legend>{queuePlans.map(row => <label key={row.id}><input type="radio" aria-label={row.label} name="queue-plan" checked={plan === row.id} onChange={() => { setPlan(row.id); onAttempt?.(true); }}/><span>{row.label}{plan === row.id && <small role="status">{row.note}</small>}</span></label>)}</fieldset>{plan && <p className="topic5-note" role="status">{ready ? "The current linked records support a monitored review-coverage pilot." : "Before recommending a change, use current linked records and inspect the post-analysis interval; preserve required review controls."}</p>}</Topic5Section>
    <button className="text-button" type="button" onClick={() => { setConfig({ ...originalQueue }); setPlan(""); onAttempt?.(false); }}>Reset lesson interactions</button></div>;
}
